server:
  port: 5000
spring:
  application:
    name: api-gateway
eureka:
  enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
    # 集群模式下配置 defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/
      defaultZone: http://localhost:7070/eureka/
zuul:
  prefix: /v1
  routes:
    service-a:  # 可自定义
      path: /service-a/**
      serviceId: service-a  # 转发到消费者 /ribbon/
    service-b:  # 可自定义
      path: /service-b/**
      serviceId: service-b  # 转发到消费者 /feign/
    service-c:  # 可自定义
      path: /service-c/**
      serviceId: service-c  # 转发到消费者 /feign/
    druid:
      path: /druid
      serviceId: service-c  # 转发到消费者 /feign/
