fss:
  active: aliyun
  aliyun:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    accessKeyId: LTAI4G9V5oKNubhNz517RpuR
    accessKeySecret: pqHsq3TONu4B8YpMctUBWWRQHuiEc7
    bucketName: barrel-stg

aliyun:
  sls:
    endpoint: cn-zhangjiakou.log.aliyuncs.com
    accessKeyId: LTAI4G9V5oKNubhNz517RpuR
    accessKeySecret: pqHsq3TONu4B8YpMctUBWWRQHuiEc7
    project: barrel
    logStore: barrel-logstore
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com
    accessKeyId: LTAI4G9V5oKNubhNz517RpuR
    accessKeySecret: pqHsq3TONu4B8YpMctUBWWRQHuiEc7
    bucketName: barrel-stg