server:
  port: 9005 #提供者的端口
spring:
  application:
    name: barrel-dictionary
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev.ecs:3306/barrel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: barrel_data
    password: Putdown#exhale6#ploys#Blunt
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
#      config:
#        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
#        file-extension: yaml
#        namespace: 7d3e5f19-a102-471a-b6e0-67bd7d1d35f3
#        group: ORDER_GROUP

  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

logging:
  level:
    org.springframework.web: DEBUG
    main.blog.mapper: trace

# mybatis
mybatis-plus:
  global-config:
    db-config:
      table-prefix: xmo_
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.github.tanxinzheng.**.model,com.github.tanxinzheng.**.entity
  mapper-locations: classpath:com/**/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'