spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xmo_demo?useUnicode:true&amp;characterEncoding:utf8
    username: root
    password: 123456
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    request-context-attribute: ctx
    enabled: true
    template-loader-path: classpath:/templates/
    classic_compatible: true

mybatis:
  typeAliasesPackage: com.**.model
  mapperLocations: classpath*:com/**/mapper/*.xml
  configLocation: mybatis-config.xml
server:
  port: 20000

