version: '3'

services:
  barrel-gateway:
    networks:
      work_net:
        ipv4_address: 172.20.0.200
    restart: always
    image: barrel/barrel-gateway:latest
    container_name: barrel-gateway
    ports:
      - "9999:9999"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  barrel-auth:
    networks:
      work_net:
        ipv4_address: 172.20.0.201
    restart: always
    image: barrel/barrel-auth:latest
    container_name: barrel-auth
    ports:
      - "10110:10110"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

networks:
  work_net:
    external: true