version: '2'

services:
  barrel-gateway:
    networks:
      work_net:
        ipv4_address: 172.20.0.200
    restart: always
    image: barrel/barrel-gateway:latest
    container_name: barrel-gateway
    tty: true
    extra_hosts:
      - "redis.docker.local:172.20.0.4"
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=--spring.profiles.active=sit,redis -Dfile.encoding=utf-8 -Dspring.cloud.nacos.config.namespace=${NACOS_CONFIG_NAMESPACE} -Dspring.cloud.nacos.discovery.namespace=${NACOS_CONFIG_NAMESPACE}

  barrel-auth:
    networks:
      work_net:
        ipv4_address: 172.20.0.202
    restart: always
    image: barrel/barrel-auth:latest
    container_name: barrel-auth
    tty: true
    extra_hosts:
      - "redis.docker.local:172.20.0.4"
    ports:
      - "9901:9901"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=--spring.profiles.active=sit,redis -Dfile.encoding=utf-8 -Dspring.cloud.nacos.config.namespace=${NACOS_CONFIG_NAMESPACE} -Dspring.cloud.nacos.discovery.namespace=${NACOS_CONFIG_NAMESPACE}

  barrel-system:
    networks:
      work_net:
        ipv4_address: 172.20.0.201
    restart: always
    image: barrel/barrel-system:latest
    container_name: barrel-system
    tty: true
    extra_hosts:
      - "redis.docker.local:172.20.0.4"
    ports:
      - "9902:9902"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=--spring.profiles.active=sit,redis,fss -Dfile.encoding=utf-8 -Dspring.cloud.nacos.config.namespace=${NACOS_CONFIG_NAMESPACE} -Dspring.cloud.nacos.discovery.namespace=${NACOS_CONFIG_NAMESPACE}

  barrel-admin:
    networks:
      work_net:
        ipv4_address: 172.20.0.203
    restart: always
    image: barrel/barrel-admin:latest
    container_name: barrel-admin
    tty: true
    ports:
      - "9998:9998"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=--spring.profiles.active=sit -Dfile.encoding=utf-8 -Dspring.cloud.nacos.config.namespace=${NACOS_CONFIG_NAMESPACE} -Dspring.cloud.nacos.discovery.namespace=${NACOS_CONFIG_NAMESPACE}
#
#  barrel-zipkin:
#    image: openzipkin/zipkin
#    container_name: barrel-zipkin
#    networks:
#      work_net:
#        ipv4_address: 172.20.0.204
#    restart: always
#    tty: true
#    ports:
#      - "9411:9411"

networks:
  work_net:
    external: true