version: '3'

services:
  boot-admin-app:
    networks:
      - txz-docker-net
    #restart: always
    image: boot-admin-app:latest
    ports:
    - "10001:8000"

networks:
  txz-docker-net:
    external: true