server:
  port: 9999 #提供者的端口
spring:
  profiles:
    active: dev
  application:
    name: barrel-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: host_route
          uri: http://www.baidu.com
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1
        # 字典服务
        - id: barrel-dictionary
          uri: lb://barrel-dictionary
          predicates:
            - Path=/auth/**
        # 认证服务
        - id: barrel-auth
          uri: lb://barrel-auth
          predicates:
            - Path=/dictionary/**
  redis:
    database: 0
    cluster:
      max-redirects: 3
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

# 聚合文档配置
barrel:
  document:
    resources:
      - name: 授权模块
        location: /barrel-auth
#      - name: 工作台模块
#        location: /barrel-desk
#      - name: 系统模块
#        location: /barrel-system
      - name: 基础模块
        location: /barrel-dictionary

management:
  endpoints:
    web:
      exposure:
        include: '*'