server:
  port: 9999 #提供者的端口
spring:
  application:
    name: barrel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: host_route
          uri: http://www.baidu.com
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1
        - id: barrel-dictionary           #网关路由到字典服务dictionary-service
          uri: lb://barrel-dictionary
          predicates:
            - Path=/dictionary/**

# 聚合文档配置
barrel:
  document:
    resources:
      - name: 授权模块
        location: /blade-auth
      - name: 工作台模块
        location: /blade-desk
      - name: 系统模块
        location: /blade-system

management:
  endpoints:
    web:
      exposure:
        include: '*'