server:
  port: 8083
  context-path: /

spring:
  http:
    encoding:
    charset: UTF-8
    enabled: true
    force: true
    mail:
        default-encoding: UTF-8
    messages:
        encoding: UTF-8

casServerUrlPrefix: http://localhost:9000
cas:
  prefixUrl: http://localhost:9000
  loginUrl: ${cas.prefixUrl}/login
  logoutUrl: ${cas.prefixUrl}/logout
  centralLogout: ${cas.prefixUrl}/logout
  serviceUrl: http://localhost:${server.port}
  callbackUrl: ${cas.serviceUrl}/callback
jwt:
  salt: cas

debug: true
