logging:
  config: classpath:logback.xml

jwt:
  salt: cas

# oss
oss:
  accessKeyId: LTAIQ9tAnQKgixOa
  accessKeySecret: SvUzBFGETJ3k9DUY0krXEKLYEpOsFF
  bucketName: xmomen-test
  endpoint: oss-cn-hangzhou.aliyuncs.com