server:
  port: 8000
#  context-path: /api

spring:
  resources:
    static-locations:
      - classpath:/static/
  profiles:
    active: ${build.profile.id:dev}, redis
  freemarker:
    enabled: true
    suffix: ftl
    settings:
      recognize_standard_file_extensions: true

# mybatis
mybatis-plus:
  global-config:
    db-config:
      table-prefix: xmo_
  type-aliases-package: com.github.tanxinzheng.**.model
  mapper-locations: classpath*:com/**/mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
