logging:
  config: classpath:logback.xml

casServerUrlPrefix: http://localhost:9000
cas:
  prefixUrl: http://localhost:9000
  loginUrl: ${cas.prefixUrl}/login
  logoutUrl: ${cas.prefixUrl}/logout
  centralLogout: ${cas.prefixUrl}/logout
  serviceUrl: http://localhost:${server.port}
  callbackUrl: ${cas.serviceUrl}/callback
jwt:
  salt: cas