logging:
  config: classpath:logback.xml

#cas:
#  server-url: http://localhost:20001
#  server-login-url: ${cas.server-url}/login
#  server-logout-url: ${cas.server-url}/logout?service=${cas.app-server-url}
#  app-server-url: http://localhost:${server.port}
#  app-login-url: /login
#  app-logout-url: /logout
#  permit-urls: /access,/anonymous # 不需要登录即可访问URL，通过,分割

jwt:
  secret: 123456
  expiration: 2 # 以小时为时间单位
  permit-urls: /nologin,/anonymous # 不需要登录即可访问URL，通过逗号分割

# oss
oss:
  accessKeyId: LTAIQ9tAnQKgixOa
  accessKeySecret: SvUzBFGETJ3k9DUY0krXEKLYEpOsFF
  bucketName: xmomen-test
  endpoint: oss-cn-hangzhou.aliyuncs.com