#logging:
#  config: classpath:logback.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmo_demo?useUnicode:true&characterEncoding:utf8&useSSL:true
    username: root
    password: 123456
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

jwt:
  secret: 123456
  permit-urls:
    - /error
    - /actuator/**
    - /auth/**
    - /index.html

    ## swagger 免登陆资源，生产环境关闭
    - /favicon.ico
    - /swagger-ui.html
    - /swagger-resources/**
    - /v2/**
    - /webjars/**

storage:
  active: aliyun
  aliyun:
    access-key-id: LTAIQ9tAnQKgixOa
    access-key-secret: SvUzBFGETJ3k9DUY0krXEKLYEpOsFF
    bucket-name: xmomen-test
    endpoint: oss-cn-hangzhou.aliyuncs.com
