#logging:
#  config: classpath:logback.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmo_demo?useUnicode:true&amp;characterEncoding:utf8&amp;useSSL:false
    username: root
    password: 123456
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）

jwt:
  secret: 123456
  permit-urls:
    - /auth/**
    - /index.html
    - /swagger-ui.html
    - /swagger-resources/**
    - /v2/**
    - /webjars/**

storage:
  active: aliyun
  aliyun:
    access-key-id: LTAIQ9tAnQKgixOa
    access-key-secret: SvUzBFGETJ3k9DUY0krXEKLYEpOsFF
    bucket-name: xmomen-test
    endpoint: oss-cn-hangzhou.aliyuncs.com
