server:
  port: 8000
#  context-path: /api

spring:
  resources:
    static-locations:
      - classpath:/static/
  profiles:
    active: ${build.profile.id}
  servlet:
    multipart:
      max-file-size: 20971520
  ######## mail configuration
  mail:
    host: smtp.mxhichina.com
    username: test@xmomen.com
    password: aaaaa888*
    properties:
      mail:
        smtp:
          auth: true
          port: 25
  cache:
    type: redis

#druid datasource
druid:
  initialSize: 10
  minIdle: 10
  maxActive: 50
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x' FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: wall,stat

# mybatis
mybatis:
  type-aliases-package: com.**.model
  mapper-locations: classpath*:com/**/mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

# security
jwt:
  secret: xmomen

jog:
  cron:
    simpleJob: 0/5 * * * * ?

# oss
oss:
  accessKeyId: LTAIQ9tAnQKgixOa
  accessKeySecret: SvUzBFGETJ3k9DUY0krXEKLYEpOsFF
  bucketName: xmomen-test
  endpoint: oss-cn-hangzhou.aliyuncs.com


job:
  cron:
    simpleJob: 0/5 * * * * ?