management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证服务
        - id: barrel-api
          uri: lb://barrel-api
          predicates:
            - Path=/barrel-api/**
          filters:
            - StripPrefix=1