management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 认证服务
        - id: barrel-auth
          uri: lb://barrel-auth
          predicates:
            - Path=/barrel-auth/**
          filters:
            - StripPrefix=1
        - id: barrel-system
          uri: lb://barrel-system
          predicates:
            - Path=/barrel-system/**
          filters:
            - StripPrefix=1
        - id: barrel-account
          uri: lb://barrel-account
          predicates:
            - Path=/barrel-account/**
          filters:
            - StripPrefix=1