spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev.local:3306/barrel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: barrel_data
    password: Putdown#exhale6#ploys#Blunt

  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    lettuce:
      pool:
        max-active:  100
        max-idle: 100
        min-idle: 50
        max-wait: 6000
    timeout: 1000

logging:
  level:
    org.springframework.web: DEBUG
    main.blog.mapper: trace
  config: classpath:logback-dev.xml
  file:
    path: .\target\logs

jwt:
  secret: 123456
  permit-urls:
    - /error
    - /actuator/**
    - /auth/**
    - /index.html
