fss:
  active: aliyun
  aliyun:
    endpoint: http://oss-cn-zhangjiakou.aliyuncs.com
    accessKeyId: LTAI4G8iZgyAVxh6L7M1bCV8
    accessKeySecret: UzKJdXOjparpRkDPfTHtLMUOozG6B7
    bucketName: barrel-stg