# mybatis
mybatis-plus:
  global-config:
    db-config:
      table-prefix: xmo_
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
      db-type: mysql
    refresh: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.github.tanxinzheng.**.model,com.github.tanxinzheng.**.entity
  mapper-locations: classpath:com/**/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    active: fss
  mail:
    nickname: IT服务助手
    username: it-support@tanxz.com
    password: R5sMyokE6e7p3uzRka6Rx559PhM9eHXE
    host: smtp.tanxz.com
    properties:
      mail.smtp.ssl.enable: true