# mybatis
mybatis-plus:
  global-config:
    db-config:
      table-prefix: xmo_
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.github.tanxinzheng.**.model,com.github.tanxinzheng.**.entity
  mapper-locations: classpath:com/**/mapper/*.xml

logging:
  level:
    org.springframework.web: DEBUG
    main.blog.mapper: trace

barrel:
  auth:
