spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev.local:3306/barrel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: barrel_data
    password: Putdown#exhale6#ploys#Blunt
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005

logging:
  level:
    org.springframework.web: DEBUG
    main.blog.mapper: trace
  config: classpath:logback-dev.xml

jwt:
  secret: 123456
  permit-urls:
    - /error
    - /actuator/**
    - /auth/**
    - /index.html

