#name: Deploy Aliyun
#
#on:
#  push:
#    branches:
#      - 1.0.0
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Barrel Framework
#        uses: actions/checkout@v2
#        with:
#          repository: tanxinzheng/barrel-framework
#          ref: 1.0.0
#          path: barrel-framework
#
#      - name: Checkout tools repo
#        uses: actions/checkout@v2
#        with:
#          path: barrel-plateform
#
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Install Barrel Framework
#        run: |
#            mvn install -f barrel-framework/pom.xml
#
#      - name: Install Barrel Platform
#        run: |
#            mvn install -f barrel-plateform/pom.xml -Pstg
#
#      - name: Copy jar to deploy directory
#        run: |
#            unzip -o barrel-plateform/barrel-system/target/barrel-system.zip -d deploy
#            unzip -o barrel-plateform/barrel-gateway/target/barrel-gateway.zip -d deploy
#            unzip -o barrel-plateform/barrel-service/barrel-module-authorization/target/barrel-system.zip -d deploy
#
#      # Deploy
#      - name: Rsync Barrel Jar
#        env:
#          DEPLOY_KEY: ${{ secrets.ALIYUN_PRI_KEY }}
#          ARGS: "-avzu --delete"
#          REMOTE_PORT: ${{ secrets.ALIYUN_ECS_PORT }}
#          REMOTE_HOST: ${{ secrets.ALIYUN_ECS_HOST }}
#          REMOTE_USER: ${{ secrets.ALIYUN_ECS_USER }}
#          SOURCE: "deploy"
#          TARGET:  "/app/deploy/"
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
#          ls
#          rsync $ARGS $SOURCE $REMOTE_USER@$REMOTE_HOST:$TARGET
#
#      - name: Restart Spring Boot Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.ALIYUN_ECS_HOST }}
#          port: ${{ secrets.ALIYUN_ECS_PORT }}
#          username: ${{ secrets.ALIYUN_ECS_USER }}
#          key: ${{ secrets.ALIYUN_PRI_KEY }}
#          script: |
#             export RUN_AS_USER=${{ secrets.ALIYUN_ECS_USER }}
#             sudo systemctl restart barrel-system
#             sudo systemctl restart barrel-system
#             sudo systemctl restart barrel-gateway
