name: Deploy Aliyun

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Barrel Framework
        uses: actions/checkout@v2
        with:
          repository: tanxinzheng/barrel-framework
          ref: 1.0.0
          path: barrel-framework

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          path: barrel-plateform

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Barrel Framework
        run: |
            mvn install -f barrel-framework/pom.xml

      - name: Install Barrel Platform
        run: |
            mvn install -f barrel-plateform/pom.xml -Pstg

      - name: Copy jar to deploy directory
        run: |
            rm -rf deploy
            mkdir deploy
            cp barrel-plateform/barrel-auth/target/barrel-auth-1.0.0-SNAPSHOT.jar deploy
            cp barrel-plateform/barrel-gateway/target/barrel-gateway.jar deploy
            cp barrel-plateform/barrel-service/barrel-module-authorization/target/barrel-system-1.0.0-SNAPSHOT.jar deploy

      # Deploy
#      - name: Deploy Barrel Jar
#        uses: easingthemes/ssh-deploy@v2.0.7
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_ECS_PRI_KEY }}
#          ARGS: "-avz --delete"
#          SOURCE: "deploy"
#          REMOTE_HOST: ${{ secrets.ALIYUN_ECS_HOST }}
#          REMOTE_USER: ${{ secrets.ALIYUN_ECS_USER }}
#          TARGET: "/app/deploy"

      - name: Scp files deploy directory
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_ECS_HOST }}
          port: ${{ secrets.ALIYUN_ECS_PORT }}
          username: ${{ secrets.ALIYUN_ECS_USER }}
          password: ${{ secrets.ALIYUN_ECS_PASSWORD }}
          source: "deploy/barrel-auth-1.0.0-SNAPSHOT.jar,deploy/barrel-gateway.jar,deploy/barrel-system-1.0.0-SNAPSHOT.jar"
          target: "/app/deploy"

#      - name: Start Spring Boot Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.ALIYUN_ECS_HOST }}
#          port: ${{ secrets.ALIYUN_ECS_PORT }}
#          username: ${{ secrets.ALIYUN_ECS_USER }}
#          password: ${{ secrets.ALIYUN_ECS_PASSWORD }}
#          script: |
#             cd /app/deploy/deploy
#             sudo ln -s  /app/deploy/deploy/barrel-auth-1.0.0-SNAPSHOT.jar  /etc/init.d/bms
#             barrel-auth-1.0.0-SNAPSHOT.jar