name: Deploy Aliyun

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Barrel Framework
        uses: actions/checkout@v2
        with:
          repository: tanxinzheng/barrel-framework
          ref: 1.0.0
          path: barrel-framework

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          path: barrel-plateform

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Barrel Framework
        run: |
            mvn install -f barrel-framework/pom.xml

      - name: Install Barrel Platform
        run: |
            mvn install -f barrel-plateform/pom.xml -Pstg

      - name: Copy jar to deploy directory
        run: |
            rm -rf deploy
            mkdir deploy
            cp barrel-plateform/barrel-auth/target/barrel-auth-1.0.0-SNAPSHOT.jar deploy
            cp barrel-plateform/barrel-gateway/target/barrel-gateway.jar deploy
            cp barrel-plateform/barrel-service/barrel-module-authorization/target/barrel-system-1.0.0-SNAPSHOT.jar deploy

      # Deploy
      - name: Deploy Barrel Jar
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_ECS_PRI_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "deploy"
          REMOTE_HOST: ${{ secrets.ALIYUN_ECS_HOST }}
          REMOTE_USER: ${{ secrets.ALIYUN_ECS_USER }}
          TARGET: "/app/deploy"