name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Barrel Framework
        uses: actions/checkout@v2
        with:
          repository: tanxinzheng/barrel-framework
          ref: 1.0.0
          path: barrel-framework

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          path: barrel-plateform

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Barrel Framework
        run: |
            mvn install -f barrel-framework/pom.xml

      - name: Package Barrel Server API
        run: |
            mvn install -f barrel-plateform/barrel-service-api/pom.xml

      - name: Package Barrel Gateway
        run: |
            mvn package -f barrel-plateform/barrel-gateway/pom.xml -Pstg

      - name: Package Barrel Auth
        run: |
            mvn package -f barrel-plateform/barrel-auth/pom.xml -Pstg

      - name: Package Barrel Module System
        run: |
            mvn package -f barrel-plateform/barrel-service/barrel-module-authorization/pom.xml -Pstg